/* THE VESTAVIA VOICE — article reader data + overlay */
const authors={
  "James Mitchell":{photo:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",bio:"Editor in Chief · City Hall"},
  "Rebecca Hollis":{photo:"https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80",bio:"Managing Editor · Development"},
  "Priya Chandra":{photo:"https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",bio:"Schools Reporter"},
  "Chris Donovan":{photo:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",bio:"Rebels Sports"},
  "Tom Alvarez":{photo:"https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80",bio:"Public Safety"},
  "Elena Park":{photo:"https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=200&q=80",bio:"Dining &amp; Business"},
  "David Kim":{photo:"https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80",bio:"Business"},
  "Monica Price":{photo:"https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?auto=format&fit=crop&w=200&q=80",bio:"Community"},
  "Aisha Warren":{photo:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",bio:"Environment &amp; Features"},
  "Harold Keene":{photo:"https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80",bio:"Columnist"},
  "Linda Ferrara":{photo:"https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80",bio:"Guest Contributor"},
  "The Editorial Board":{photo:"https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=200&q=80",bio:"Voice Editorial Board"},
  "Eleanor Whitaker":{photo:"",bio:"Cahaba Heights Reader"},
  "The Voice":{photo:"",bio:"Obituaries"}
};
const articles={
  corridor:{category:"Government · Exclusive",headline:"Council green-lights $14M Cahaba Heights corridor overhaul after two years of hearings",deck:"The long-debated plan will widen sidewalks, add a protected bike lane, and reroute truck traffic — but residents on Dolly Ridge Road say they're still waiting on a promised traffic study.",author:"James Mitchell",initials:"JM",date:"April 22, 2026 · 4 hours ago",readTime:"8 min read",hero:"https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?auto=format&fit=crop&w=1600&q=85",caption:"Mayor Cunningham addresses residents at Tuesday's council session.",tags:["Cahaba Heights","City Council","Infrastructure"],
    body:`<p>The Vestavia Hills City Council voted 4-1 Tuesday night to approve the long-debated Cahaba Heights corridor improvement plan, clearing the way for $14 million in roadwork, pedestrian upgrades, and truck rerouting along the busy commercial stretch.</p><p>The approval caps nearly two years of public hearings, revised designs, and pushback from residents whose homes back up to the corridor. Mayor Ashley Cunningham called the vote "a victory for walkability and for the neighborhoods we've heard from."</p><blockquote>We're not against the project. We just want the data the city promised.</blockquote><p>But residents on Dolly Ridge Road, who spoke again Tuesday, say the plan still hasn't addressed the traffic study they were promised at last fall's listening session.</p><h3>What's in the plan</h3><p>The approved design widens sidewalks to 8 feet along Cahaba Heights Road, installs a protected bike lane on the north side, and designates alternative truck routes through the industrial access road. Construction is expected to begin in late fall 2026 and phase over 18 months.</p><h3>Funding and next steps</h3><p>Roughly 60% of the $14 million will come from the city's general infrastructure fund, with the balance split between state DOT match and a federal Complete Streets grant secured in late 2025.</p><p>A community information session is scheduled for May 7 at the Cahaba Heights branch library.</p>`},
  budget:{category:"City Hall",headline:"Mayor outlines 2027 budget priorities: parks, roads, body cameras",deck:"Proposed $92M operating budget holds the millage rate steady while adding four patrol positions and $2.1M in park improvements.",author:"James Mitchell",initials:"JM",date:"April 21, 2026 · Yesterday",readTime:"6 min read",hero:"https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=1600&q=85",caption:"Mayor Cunningham delivers the annual budget address.",tags:["Budget","Mayor","Parks"],
    body:`<p>Mayor Ashley Cunningham on Monday unveiled a proposed 2027 fiscal year budget totaling $92 million, a 4.8% increase over current spending that holds the city's property tax rate flat.</p><p>Speaking at City Hall, Cunningham framed the budget around three priorities: public safety, parks, and pavement.</p><h3>Public safety</h3><p>The proposal adds four patrol officers and completes funding for the body-camera rollout first announced in 2024.</p><h3>Parks and rec</h3><p>Wald Park headlines $2.1 million in park improvements, including a renovated amphitheater, new pickleball courts, and ADA-compliant pathways.</p><p>Council holds its first public hearing May 12. Final adoption is scheduled for June 23.</p>`},
  zoning:{category:"City Hall",headline:"Zoning commission recommends approval of Crosshaven mixed-use rezone",deck:"A 4-1 recommendation sends the contested 3.2-acre Crosshaven Drive rezone to council for a final vote next month.",author:"Rebecca Hollis",initials:"RH",date:"April 20, 2026",readTime:"5 min read",hero:"https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=1600&q=85",caption:"The Crosshaven Drive parcel under consideration.",tags:["Zoning","Development"],
    body:`<p>The Vestavia Hills Planning and Zoning Commission voted 4-1 on Thursday to recommend approval of a mixed-use rezone at 3014 Crosshaven Drive, clearing a procedural hurdle that sends the application to City Council for a final vote on May 13.</p><p>The 3.2-acre parcel, currently zoned low-density residential, would shift to a mixed-use designation allowing a 48-unit townhome development with ground-floor retail.</p><blockquote>This is infill done thoughtfully. It's not a giveaway — but it's also not a project we should walk away from.</blockquote><p>Neighborhood opposition focused on traffic and school capacity. The applicant has committed to a $180,000 intersection improvement and a proffer restricting unit counts.</p>`},
  townhall:{category:"City Hall",headline:"Residents pack town hall over proposed stormwater utility fee",deck:"The proposed $6.50/month stormwater utility fee would fund drainage upgrades — but residents pressed officials on why it isn't already covered.",author:"James Mitchell",initials:"JM",date:"April 17, 2026",readTime:"7 min read",hero:"https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?auto=format&fit=crop&w=1600&q=85",caption:"Overflow crowd at Saturday's town hall.",tags:["Stormwater","Town Hall"],
    body:`<p>More than 250 residents packed the municipal building Saturday morning for a town hall on a proposed stormwater utility fee, with most expressing skepticism of a $6.50 monthly charge.</p><p>City engineer Marcus Odell walked the crowd through the drainage backlog — roughly $18 million in documented needs across 14 sub-basins.</p><h3>The case for the fee</h3><p>The proposed structure would charge properties based on impervious surface area. The fee would generate roughly $2.8 million annually.</p>`},
  stem:{category:"Schools",headline:"Liberty Park Middle earns statewide recognition for STEM program",deck:"Alabama State Department of Education named the school among five recipients of its 2026 Innovation Award.",author:"Priya Chandra",initials:"PC",date:"April 22, 2026 · 6 hours ago",readTime:"5 min read",hero:"https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1600&q=85",caption:"Students in the school's new robotics lab.",tags:["Schools","Liberty Park","STEM"],
    body:`<p>Liberty Park Middle School has been named one of five recipients of the Alabama State Department of Education's 2026 Innovation Award, recognition that Principal Cara Whitfield called "a validation of five years of quiet work."</p><h3>How it works</h3><p>Students spend the last period of each week on interdisciplinary projects.</p><blockquote>This isn't about technology for its own sake. It's about asking real questions.</blockquote><p>The recognition comes with a $75,000 grant for the school's makerspace.</p>`},
  principal:{category:"Schools",headline:"VHHS principal Dr. Karen Shelton announces retirement after 11 years",deck:"Shelton, who has led the high school since 2015, will step down at the end of the 2026-2027 school year.",author:"Priya Chandra",initials:"PC",date:"April 18, 2026",readTime:"6 min read",hero:"https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1600&q=85",caption:"Dr. Karen Shelton outside Vestavia Hills High School.",tags:["VHHS","Principal","Retirement"],
    body:`<p>Vestavia Hills High School principal Dr. Karen Shelton will retire at the conclusion of the 2026-2027 academic year, ending an 11-year tenure that saw the school's enrollment grow, its graduation rate climb, and its competitive-academic reputation solidify.</p><p>Shelton, 62, announced the decision in a letter to families Thursday evening. "This community gave me everything," she wrote.</p><h3>Search timeline</h3><p>Superintendent Todd Freeman said the district will begin a nationwide search in early fall.</p>`},
  theater:{category:"Schools",headline:"VHHS theater program previews spring production of 'Our Town'",deck:"Director Meg Arellano's minimalist staging leans into the play's meditative center. Opening night is Friday.",author:"Priya Chandra",initials:"PC",date:"April 20, 2026",readTime:"4 min read",hero:"https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1600&q=85",caption:"Cast members rehearse.",tags:["VHHS","Theater"],
    body:`<p>The Vestavia Hills High School theater program opens its spring production of Thornton Wilder's <em>Our Town</em> Friday night.</p><p>Director Meg Arellano said she wanted to honor Wilder's stage directions — which famously call for almost no set at all. "We've leaned into that."</p>`},
  ptaprofile:{category:"Schools",headline:"Inside the PTA that raised $340K last year — and what they spent it on",deck:"Vestavia Hills Elementary East's PTA operates less like a parent group and more like a small nonprofit.",author:"Priya Chandra",initials:"PC",date:"April 13, 2026",readTime:"7 min read",hero:"https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?auto=format&fit=crop&w=1600&q=85",caption:"Elementary East volunteers at the spring carnival.",tags:["PTA","Fundraising"],
    body:`<p>When people hear that Vestavia Hills Elementary East's parent-teacher association raised $340,000 last year, they usually assume a gala or a golf tournament. Neither is involved.</p><h3>The model</h3><p>A $45 annual family membership covers the PTA's baseline budget. Restaurant spirit nights, the book fair, and a spring carnival do the rest.</p><p>The money funded 26 classroom grants, two new STEM carts, teacher appreciation, and a $48,000 playground contribution.</p>`},
  bandhonor:{category:"Schools",headline:"VHHS band selected to perform at state conference",deck:"The Wind Ensemble is one of six high school groups chosen statewide to perform at AMEA in January.",author:"Priya Chandra",initials:"PC",date:"April 6, 2026",readTime:"4 min read",hero:"https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?auto=format&fit=crop&w=1600&q=85",caption:"The wind ensemble rehearses.",tags:["VHHS","Band","AMEA"],
    body:`<p>The Vestavia Hills High School Wind Ensemble has been selected as one of six high school performing groups statewide invited to perform at the 2027 Alabama Music Educators Association conference in January.</p><p>Director David Lin called it "the biggest thing that's happened to this program in 20 years."</p>`},
  rebels:{category:"Sports",headline:"Rebels baseball clinches region, heads to state playoffs undefeated in area play",deck:"Senior ace Jordan Bell threw his fifth complete game in Tuesday's 6-1 win over Thompson.",author:"Chris Donovan",initials:"CD",date:"April 21, 2026 · 12 hours ago",readTime:"6 min read",hero:"https://images.unsplash.com/photo-1508344928928-7165b67de128?auto=format&fit=crop&w=1600&q=85",caption:"Jordan Bell delivers a pitch.",tags:["Rebels","Baseball"],
    body:`<p>For the second time in three years, the Vestavia Hills Rebels are region champions — and this time, they're entering the state playoffs without a single area loss on the ledger.</p><blockquote>He's pitching like a kid who knows this is his last time doing this.</blockquote><h3>By the numbers</h3><p>The Rebels finished 24-4, 10-0 in area. Bell leads with a 0.92 ERA. Cal McIntyre is hitting .438.</p>`},
  track:{category:"Sports",headline:"Rebels track dominates Over the Mountain Invitational",deck:"Senior Maya Obi won the 400m and anchored the victorious 4x400 relay as Vestavia piled up 148 team points.",author:"Chris Donovan",initials:"CD",date:"April 15, 2026",readTime:"5 min read",hero:"https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1600&q=85",caption:"Maya Obi anchors the winning 4x400 relay.",tags:["Track","OTM"],
    body:`<p>Vestavia Hills won its fifth straight Over the Mountain Invitational Saturday, piling up 148 team points — 32 ahead of runner-up Hoover.</p><p>Senior Maya Obi was the day's top individual performer, winning the 400m in 54.22 and anchoring the victorious 4x400 relay.</p>`},
  lacrosse:{category:"Sports",headline:"Lacrosse falls to Mountain Brook in overtime thriller",deck:"Mountain Brook's Will Parsons scored with 48 seconds left in the second overtime.",author:"Chris Donovan",initials:"CD",date:"April 17, 2026",readTime:"5 min read",hero:"https://images.unsplash.com/photo-1526232684352-b12d8f7ac1a3?auto=format&fit=crop&w=1600&q=85",caption:"The Rebels fall 11-8 at home.",tags:["Lacrosse","Mountain Brook"],
    body:`<p>Mountain Brook attacker Will Parsons scored the game-winner with 48 seconds left in the second overtime Wednesday night, lifting the Spartans to an 11-8 win over Vestavia Hills.</p><p>Rebels senior Max Holloway finished with four goals and two assists.</p>`},
  softball:{category:"Sports",headline:"Softball sweeps Hoover doubleheader behind Dolan's no-hitter",deck:"Junior Ellie Dolan threw a 12-strikeout no-hitter in game one as the Rebels swept rival Hoover.",author:"Chris Donovan",initials:"CD",date:"April 14, 2026",readTime:"5 min read",hero:"https://images.unsplash.com/photo-1508344928928-7165b67de128?auto=format&fit=crop&w=1600&q=85",caption:"Ellie Dolan celebrates.",tags:["Softball","Hoover","No-hitter"],
    body:`<p>Junior right-hander Ellie Dolan delivered the performance of her career Tuesday night, tossing a 12-strikeout no-hitter in a 4-0 win over rival Hoover.</p><p>Vestavia won the second game 7-2 behind three hits from senior Reagan Dobbs.</p>`},
  tennis:{category:"Sports",headline:"Boys tennis locks up top seed ahead of sectionals",deck:"A 7-2 win over Tuscaloosa secures the top seed for sectionals.",author:"Chris Donovan",initials:"CD",date:"April 12, 2026",readTime:"4 min read",hero:"https://images.unsplash.com/photo-1622279457486-28f24ae71dea?auto=format&fit=crop&w=1600&q=85",caption:"Senior Sam Cho serves.",tags:["Tennis","Sectionals"],
    body:`<p>The Vestavia boys tennis team clinched the top seed for next week's sectional tournament with a 7-2 win over Tuscaloosa County at home Monday.</p><p>Senior Sam Cho, ranked No. 2 in Class 7A, cruised at first singles. The Rebels swept all three doubles lines.</p>`},
  patchwork:{category:"Business",headline:"Patchwork Farms reports record leasing activity in Q1 2026",deck:"Office vacancy drops below 6% as three tenants finalize long-term leases.",author:"David Kim",initials:"DK",date:"April 22, 2026 · 5 hours ago",readTime:"5 min read",hero:"https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=85",caption:"The Patchwork Farms office campus.",tags:["Business","Office"],
    body:`<p>Patchwork Farms, the Vestavia Hills office campus that languished at 22% vacancy as recently as 2023, closed the first quarter of 2026 with occupancy at 94% — its highest level in seven years.</p><h3>What's driving the shift</h3><p>Landlord Calypso Partners attributed the turnaround to improved amenities and a softening of downtown office rents.</p><p>Average rents at the campus climbed 8% year-over-year, reaching $27 per square foot on new leases.</p>`},
  smallbiz:{category:"Business",headline:"Three Vestavia businesses named Chamber's Small Business of the Year finalists",deck:"Heritage Coffee, Daniel George Salon, and Rowan Tire have been named finalists, chosen from more than 40 nominations.",author:"David Kim",initials:"DK",date:"April 19, 2026",readTime:"4 min read",hero:"https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1600&q=85",caption:"Storefronts along Montgomery Highway.",tags:["Chamber","Small Business"],
    body:`<p>The Vestavia Hills Chamber of Commerce announced three finalists for its 2026 Small Business of the Year award: Heritage Coffee, Daniel George Salon, and Rowan Tire — chosen from 42 nominations, the chamber's highest total on record.</p><p>The winner will be announced at the chamber's May 18 awards ceremony at the Country Club of Birmingham.</p>`},
  groundbreaking:{category:"Business",headline:"Vestavia City Center breaks ground May 15, tenants confirmed",deck:"The three-phase, $62M development announces its first wave of tenants as site work begins next month.",author:"Rebecca Hollis",initials:"RH",date:"April 22, 2026",readTime:"6 min read",hero:"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=85",caption:"Rendering of the planned City Center plaza.",tags:["Development","City Center"],
    body:`<p>After three years of planning, the long-awaited Vestavia City Center development is set to break ground May 15.</p><h3>Phase one tenants</h3><p>Announced tenants include a regional coffee roaster, a boutique fitness studio, and a sit-down restaurant operator currently based in Homewood.</p>`},
  bank:{category:"Business",headline:"Community bank opens Vestavia branch, first in the 280 corridor",deck:"Shelby State Bank opens its seventh branch at Montgomery Highway and Rocky Ridge.",author:"David Kim",initials:"DK",date:"April 11, 2026",readTime:"4 min read",hero:"https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?auto=format&fit=crop&w=1600&q=85",caption:"Shelby State Bank's new Montgomery Highway branch.",tags:["Banking","Branch"],
    body:`<p>Shelby State Bank opened its seventh branch this week at the corner of Montgomery Highway and Rocky Ridge — the community bank's first in the busy 280 corridor.</p>`},
  rowan:{category:"Dining",headline:"New farm-to-table restaurant opens on Montgomery Highway this weekend",deck:"Chef Marcus Baldwin brings fine dining from Birmingham's Southside to Vestavia with \"Rowan.\"",author:"Elena Park",initials:"EP",date:"April 22, 2026 · 2 hours ago",readTime:"6 min read",hero:"https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1600&q=85",caption:"A plated course from Rowan's soft-opening dinner.",tags:["Dining","Restaurants"],
    body:`<p>Chef Marcus Baldwin will open the doors of Rowan — his long-teased Vestavia Hills restaurant — Friday night, bringing to Montgomery Highway a 60-seat fine-dining concept.</p><h3>The menu</h3><p>Opening dishes include a charred cauliflower with pecan romesco, a dry-aged ribeye from Stone Hollow Farms, and a trout preparation.</p><blockquote>I'm not interested in writing a menu in January for April.</blockquote><p>Entrees land between $28 and $54. A five-course tasting menu is available for $85.</p>`},
  cafes:{category:"Dining",headline:"Five best cafés in Vestavia, ranked",deck:"We spent a month visiting every serious coffee shop in the city. Here's how they stack up.",author:"Elena Park",initials:"EP",date:"April 16, 2026",readTime:"7 min read",hero:"https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=85",caption:"A pour-over at Heritage Coffee.",tags:["Cafés","Coffee"],
    body:`<p>Over the last month, we visited every café in Vestavia with a pour-over bar or a serious espresso program.</p><h3>1. Heritage Coffee</h3><p>The runaway winner. House-roasted beans, rotating single-origins, and the best flat white in the city.</p><h3>2. Cala Coffee</h3><p>A close second for atmosphere. Pastries from a local bakery.</p><h3>3. Whammy Coffee</h3><p>Newer entry. Excellent cold brew.</p>`},
  oldbakery:{category:"Dining",headline:"Continental Bakery marks 40 years with a weeklong celebration",deck:"The Birmingham institution brings its 40th-anniversary festivities to its Vestavia location starting Monday.",author:"Elena Park",initials:"EP",date:"April 10, 2026",readTime:"5 min read",hero:"https://images.unsplash.com/photo-1568254183919-78a4f43a2877?auto=format&fit=crop&w=1600&q=85",caption:"The bakery's classic chocolate croissants.",tags:["Continental Bakery","Anniversary"],
    body:`<p>Continental Bakery celebrates 40 years in business this year, and the Birmingham institution is bringing a full week of festivities to its Vestavia location starting Monday.</p><p>Founder Carole Griffin said the plan includes daily specials, discounted croissants, a book signing, and a Friday evening party.</p>`},
  breakfast:{category:"Dining",headline:"The definitive Vestavia breakfast tour: eight spots worth the drive",deck:"From hash brown casserole to country ham biscuits, we ate our way through eight beloved morning spots.",author:"Elena Park",initials:"EP",date:"April 3, 2026",readTime:"9 min read",hero:"https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=1600&q=85",caption:"A classic Vestavia biscuit-and-gravy plate.",tags:["Breakfast","Guide"],
    body:`<p>Vestavia isn't typically thought of as a breakfast town, which is odd given how many great morning-only spots dot the corridor.</p><p>A few highlights: Niki's West, Homewood Gourmet, Coffee Rush for the breakfast burrito, Bogue's for the classic diner experience, and Edgar's Bakery.</p>`},
  realestate:{category:"Real Estate",headline:"Home prices up 4.2% year-over-year in 35216 ZIP, inventory tightens again",deck:"Median sale price crosses $570K for the first time as spring market kicks into gear.",author:"Rebecca Hollis",initials:"RH",date:"April 20, 2026 · 2 days ago",readTime:"5 min read",hero:"https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1600&q=85",caption:"A listed home in Vestavia Heights.",tags:["Real Estate","Housing"],
    body:`<p>The median sale price for single-family homes in the 35216 ZIP code crossed $570,000 in March, up 4.2% year-over-year and the highest figure on record for the area.</p><p>At the same time, active listings fell to 48 — a 12% decline from the same month last year.</p>`},
  neighborhoods:{category:"Real Estate",headline:"Which Vestavia neighborhoods are actually appreciating? We ran the numbers",deck:"We pulled five years of sales data across Vestavia's 18 named neighborhoods.",author:"Rebecca Hollis",initials:"RH",date:"April 9, 2026",readTime:"8 min read",hero:"https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=1600&q=85",caption:"Homes in Liberty Park.",tags:["Neighborhoods","Data"],
    body:`<p>Everyone has a theory about which Vestavia neighborhoods are rising and which are flat. We pulled five years of closed-sale data.</p><h3>The top five</h3><p>Liberty Park leads with 38% appreciation over five years, followed by Cahaba Heights (32%), Ashford Grove (29%), Rocky Ridge (27%), and Altadena Valley (24%).</p>`},
  taxreassess:{category:"Real Estate",headline:"Property tax reassessments are out — here's what to check and how to appeal",deck:"Jefferson County reassessment notices went out this week. Here's what to look for.",author:"Rebecca Hollis",initials:"RH",date:"April 5, 2026",readTime:"6 min read",hero:"https://images.unsplash.com/photo-1460472178825-e5240623afd5?auto=format&fit=crop&w=1600&q=85",caption:"The Jefferson County tax assessor's office.",tags:["Property Tax","Reassessment"],
    body:`<p>Jefferson County's 2026 property tax reassessment notices went out this week, and for many Vestavia homeowners, the jump was significant.</p><h3>What to check first</h3><p>Square footage, bedroom count, and any permit history noted on the assessor's record.</p>`},
  dogwood:{category:"Community",headline:"Dogwood Festival returns to Wald Park with record 200 vendors",deck:"Proceeds from the three-day event will benefit the Vestavia Hills Library foundation.",author:"Monica Price",initials:"MP",date:"April 21, 2026",readTime:"4 min read",hero:"https://images.unsplash.com/photo-1508182311256-e3f8ae66e7d1?auto=format&fit=crop&w=1600&q=85",caption:"Dogwoods in full bloom at Wald Park.",tags:["Community","Wald Park"],
    body:`<p>The 27th annual Dogwood Festival returns to Wald Park May 1-3 with a record 200 confirmed vendors — 30 more than last year.</p><p>The three-day event will feature live music across two stages, a juried arts-and-crafts market, a children's activity zone, and food trucks.</p>`},
  shadescreek:{category:"Environment",headline:"Shades Creek watershed volunteers complete 18-month cleanup milestone",deck:"Over 12 tons of debris removed from tributaries stretching from Mountain Brook to Hoover.",author:"Aisha Warren",initials:"AW",date:"April 21, 2026",readTime:"7 min read",hero:"https://images.unsplash.com/photo-1534093607318-f025413f49cb?auto=format&fit=crop&w=1600&q=85",caption:"Volunteers clear debris.",tags:["Environment","Shades Creek"],
    body:`<p>What started as a four-person weekend effort in October 2024 has grown into one of the largest volunteer conservation projects the Shades Creek watershed has ever seen.</p><p>Over 18 months, more than 340 volunteers logged over 2,100 hours removing roughly 12 tons of debris.</p><blockquote>People think creeks clean themselves. They don't.</blockquote>`},
  bodycam:{category:"Public Safety",headline:"VHPD rolls out body-cam program, full deployment by July",deck:"Chief Keating says the rollout has been budgeted since 2024 and will cover all patrol officers.",author:"Tom Alvarez",initials:"TA",date:"April 21, 2026",readTime:"7 min read",hero:"https://images.unsplash.com/photo-1551617474-c68b4d747d61?auto=format&fit=crop&w=1600&q=85",caption:"A VHPD patrol vehicle.",tags:["VHPD","Public Safety"],
    body:`<p>The Vestavia Hills Police Department has begun deploying body-worn cameras to patrol officers, a program Chief David Keating said will cover the entire patrol division by early July.</p><blockquote>Transparency and officer safety aren't opposing values.</blockquote><p>Civilian review of released footage will continue through the existing complaint review process.</p>`},
  citycenter:{category:"Development",headline:"Vestavia City Center mixed-use project breaks ground next month",deck:"The three-phase, $62M development will bring 180 residences and a public plaza to the former Books-a-Million site.",author:"Rebecca Hollis",initials:"RH",date:"April 22, 2026",readTime:"6 min read",hero:"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=85",caption:"Rendering of the planned City Center plaza.",tags:["Development","Real Estate"],
    body:`<p>After three years of planning, the long-awaited Vestavia City Center development is set to break ground May 15.</p><p>The $62 million mixed-use project will unfold in three phases over roughly 36 months.</p>`},
  opinion:{category:"Opinion · Column",headline:"The quiet cost of delayed sidewalks on Rocky Ridge",deck:"We've been promising this for a decade. Every year of delay has a price.",author:"Harold Keene",initials:"HK",date:"April 20, 2026",readTime:"4 min read",hero:"https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?auto=format&fit=crop&w=1600&q=85",caption:"A stretch of Rocky Ridge Road with no sidewalk.",tags:["Opinion","Sidewalks"],
    body:`<p>In 2016, the city adopted a Complete Streets resolution. In 2018, we funded a sidewalk master plan. In 2020, we formed a walkability committee. In 2023, we commissioned an engineering study. And in 2026, the 900-foot gap between Rocky Ridge Elementary and the nearest crosswalk remains exactly where it was.</p><blockquote>Every year of delay has a cost. Most of it is human.</blockquote><p>We should have built this ten years ago. We should build it now.</p><p><em>Harold Keene is a former chair of the city's walkability committee.</em></p>`},
  guest:{category:"Opinion · Guest Essay",headline:"A former council member on why the corridor plan matters",deck:"Infrastructure decisions outlive council terms. This one deserved the scrutiny it got.",author:"Linda Ferrara",initials:"LF",date:"April 22, 2026",readTime:"5 min read",hero:"https://images.unsplash.com/photo-1573164574572-cb89e39749b4?auto=format&fit=crop&w=1600&q=85",caption:"Cahaba Heights Road.",tags:["Opinion","Corridor"],
    body:`<p>I spent eight years on this council, and I can tell you: most votes don't matter as much as people think. The Cahaba Heights corridor vote was an exception.</p><p>Infrastructure decisions don't expire with terms of office. They shape the next thirty years.</p>`},
  editorial:{category:"Editorial",headline:"Our View: Body cameras are a starting line, not a finish",deck:"The rollout is a meaningful step. What happens with the footage is the real test.",author:"The Editorial Board",initials:"EB",date:"April 20, 2026",readTime:"4 min read",hero:"https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1600&q=85",caption:"",tags:["Editorial","VHPD"],
    body:`<p>Body cameras are coming to Vestavia Hills Police Department patrol officers, and for that we credit Chief Keating and a city council that has been steadily, if quietly, moving this program along since 2024.</p><p>But cameras are only ever as useful as the policies around the footage they produce.</p>`},
  letter1:{category:"Reader Letter",headline:"Letter: My grandchildren deserve cleaner creeks too",deck:"Reader response to the Shades Creek cleanup coverage.",author:"Eleanor Whitaker",initials:"EW",date:"April 18, 2026",readTime:"3 min read",hero:"https://images.unsplash.com/photo-1445796886651-d31463b30e24?auto=format&fit=crop&w=1600&q=85",caption:"",tags:["Letter","Environment"],
    body:`<p>I am 81 years old and have lived near Shades Creek my entire life. I watched that creek decline in my adulthood, and I am watching it come back in my old age, thanks to volunteers whose names I will never know.</p><p>That is worth something.</p>`},
  obit_hartsfield:{category:"Obituary",headline:"William \"Bill\" Hartsfield, 84",deck:"Retired Vestavia Hills teacher and founding member of the Historical Society. Service to be held Saturday.",author:"The Voice",initials:"VV",date:"April 19, 2026",readTime:"4 min read",hero:"https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1600&q=85",caption:"",tags:["Obituary"],
    body:`<p>William "Bill" Hartsfield, 84, passed peacefully on April 19, 2026, surrounded by family at his home in Cahaba Heights.</p><p>A retired Vestavia Hills teacher and founding member of the Historical Society, Bill is remembered for four decades of service to local schools.</p><p>He is survived by his wife of 58 years, Marjorie; three children; and six grandchildren.</p><p>A celebration of life will be held Saturday at 11 a.m. at Shades Valley Presbyterian Church.</p>`},
  obit_thompson:{category:"Obituary",headline:"Eleanor Grace Thompson, 91",deck:"A beloved piano instructor who taught three generations of Vestavia families over her 52-year career.",author:"The Voice",initials:"VV",date:"April 18, 2026",readTime:"3 min read",hero:"https://images.unsplash.com/photo-1541689221361-ad95003448dc?auto=format&fit=crop&w=1600&q=85",caption:"",tags:["Obituary"],
    body:`<p>Eleanor Grace Thompson, 91, of Cahaba Heights, passed away peacefully on April 18, 2026.</p><p>A beloved piano instructor who taught three generations of Vestavia families over her 52-year career, Eleanor was known for her gentle patience.</p>`},
  obit_carlisle:{category:"Obituary",headline:"Reverend Thomas Carlisle, 78",deck:"Pastor Emeritus of Covenant Presbyterian and longtime Vestavia community leader.",author:"The Voice",initials:"VV",date:"April 14, 2026",readTime:"4 min read",hero:"https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&w=1600&q=85",caption:"",tags:["Obituary"],
    body:`<p>Reverend Thomas Carlisle, 78, Pastor Emeritus of Covenant Presbyterian Church, passed away at his home April 14, 2026.</p><p>He is remembered for a 32-year pulpit ministry and for founding the city's interfaith food ministry in 2001.</p>`}
};

function openReader(id){
  const a=articles[id];if(!a)return;
  document.getElementById('reader-category').textContent=a.category;
  document.getElementById('reader-headline').textContent=a.headline;
  document.getElementById('reader-deck').textContent=a.deck||'';
  document.getElementById('reader-author').textContent=a.author;
  document.getElementById('reader-date').textContent=a.date;
  const avatar=document.getElementById('reader-avatar');
  const aPhoto=(authors[a.author]||{}).photo;
  if(aPhoto){avatar.innerHTML='<img src="'+aPhoto+'" alt="'+a.author+'" style="width:100%;height:100%;object-fit:cover;border-radius:50%">';avatar.style.padding='0'}
  else{avatar.textContent=a.initials;avatar.style.padding=''}
  document.getElementById('reader-hero-img').src=a.hero;
  document.getElementById('reader-hero-img').alt=a.headline;
  document.getElementById('reader-hero-caption').textContent=a.caption||'';
  document.getElementById('reader-hero-caption').style.display=a.caption?'':'none';
  document.getElementById('reader-content').innerHTML=a.body;
  document.getElementById('reader-read-time').textContent=a.readTime;
  const tags=document.getElementById('reader-tags');tags.innerHTML='';
  (a.tags||[]).forEach(t=>{const s=document.createElement('span');s.className='reader-tag';s.textContent=t;tags.appendChild(s)});
  document.getElementById('reader-overlay').classList.add('open');
  document.body.classList.add('reader-open');
  document.getElementById('reader-overlay').scrollTop=0;
}
function closeReader(){
  document.getElementById('reader-overlay').classList.remove('open');
  document.body.classList.remove('reader-open');
}

(function(){
  const html=`<div class="reader-overlay" id="reader-overlay" onclick="if(event.target===this)closeReader()">
    <div class="reader" id="reader">
      <button class="reader-close" onclick="closeReader()" aria-label="Close">×</button>
      <div class="reader-hero" id="reader-hero">
        <img id="reader-hero-img" src="" alt="">
        <div class="reader-hero-caption" id="reader-hero-caption"></div>
      </div>
      <div class="reader-body">
        <span class="reader-category" id="reader-category"></span>
        <h1 class="reader-headline" id="reader-headline"></h1>
        <p class="reader-deck" id="reader-deck"></p>
        <div class="reader-meta">
          <div class="reader-byline">
            <div class="reader-avatar" id="reader-avatar"></div>
            <div>
              <div class="reader-author-name" id="reader-author"></div>
              <div class="reader-author-date" id="reader-date"></div>
            </div>
          </div>
          <div class="reader-actions">
            <button class="reader-icon-btn" title="Save" onclick="event.stopPropagation()">♥</button>
            <button class="reader-icon-btn" title="Share" onclick="event.stopPropagation();navigator.clipboard&&navigator.clipboard.writeText(location.href);this.textContent='✓'">⇪</button>
            <button class="reader-icon-btn" title="Print" onclick="event.stopPropagation();window.print()">⎙</button>
          </div>
        </div>
        <div class="reader-content" id="reader-content"></div>
        <div class="reader-footer">
          <div class="reader-tags" id="reader-tags"></div>
          <div id="reader-read-time"></div>
        </div>
      </div>
    </div>
  </div>`;
  function init(){
    document.body.insertAdjacentHTML('beforeend',html);
    document.querySelectorAll('[data-article]').forEach(el=>{
      el.addEventListener('click',function(e){
        if(e.target.tagName==='A'&&e.target.getAttribute('href')&&e.target.getAttribute('href')!=='#')return;
        e.preventDefault();
        openReader(this.dataset.article);
      });
    });
    document.addEventListener('keydown',e=>{if(e.key==='Escape')closeReader()});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);
  else init();
})();
