// GENERATED by build-shop.py — do not hand-edit. Rerun the script instead.
window.TT_PRODUCTS = [
 {
  "name": "Millie Sweatshirt Bodda Getta",
  "style": null,
  "price": "49",
  "sizes": "S, M, L, XL",
  "desc": "Sequins on Sleeves, Fuzzy sparkly lettering (Bodda Getta)\n62% Poly, 33% Rayon, 5% Spandex\nHand Wash (I use machine with hand wash cycle in lingerie bag)\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); Generously sized",
  "cat": "Sweatshirts & Sweaters",
  "img": "img/products/millie-sweatshirt-bodda-getta.jpg"
 },
 {
  "name": "Celia Sweater Vest",
  "style": null,
  "price": "62",
  "sizes": "XS, S, M, L, XL",
  "desc": "50% Viscose, 28% Poly, 22% Nylon\nMachine Wash Cold\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); True To Size",
  "cat": "Sweatshirts & Sweaters",
  "img": "img/products/celia-sweater-vest.jpg"
 },
 {
  "name": "Tina Top WDE",
  "style": null,
  "price": "63",
  "sizes": "XS, S, M, L, XL",
  "desc": "Sequin/Rhinestone Lettering\n62% Poly, 33% Rayon, 5% Spandex\nHand Wash (I use machine with hand wash cycle in lingerie bag)\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); Generously sized",
  "cat": "Tops",
  "img": "img/products/tina-top-wde.jpg"
 },
 {
  "name": "Sarah Sweatshirt Power Stripe",
  "style": null,
  "price": "79",
  "sizes": "S, M, L, XL, 1X, 2X",
  "desc": "Beaded Power Stripe/Embroidered Lettering\n62% Poly, 33% Rayon, 5% Spandex\nHand Wash (I use machine with hand wash cycle in lingerie bag)\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); 1X (16); 2X (18) Generously sized",
  "cat": "Sweatshirts & Sweaters",
  "img": "img/products/sarah-sweatshirt-power-stripe.jpg"
 },
 {
  "name": "Sarah Sweatshirt Fearless & True",
  "style": null,
  "price": "79",
  "sizes": "S, M, L, XL, 1X, 2X",
  "desc": "Sequin/Rhinestone on Sleeves, Sequin Lettering\n62% Poly, 33% Rayon, 5% Spandex\nHand Wash (I use machine with hand wash cycle in lingerie bag)\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); 1X (16); 2X (18) Generously sized",
  "cat": "Sweatshirts & Sweaters",
  "img": "img/products/sarah-sweatshirt-fearless-true.jpg"
 },
 {
  "name": "Sarah Sweatshirt Basketball",
  "style": null,
  "price": "68",
  "sizes": "S, M, L, XL, 1X",
  "desc": "Sequin Designs\n62% Poly, 33% Rayon, 5% Spandex\nHand Wash (I use machine with hand wash cycle in lingerie bag)\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14);  1X (16-18) Generously sized",
  "cat": "Sweatshirts & Sweaters",
  "img": "img/products/sarah-sweatshirt-basketball.jpg"
 },
 {
  "name": "Hannah Sweater",
  "style": null,
  "price": "55",
  "sizes": "S, M, L",
  "desc": "50% Viscose, 28% Poly, 22% Nylon\nMachine Wash Cold\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); True To Size",
  "cat": "Sweatshirts & Sweaters",
  "img": "img/products/hannah-sweater.jpg"
 },
 {
  "name": "Anna Dress",
  "style": null,
  "price": "45",
  "sizes": "XS, S, M, L, XL, XXL",
  "desc": "Sequin Designs\n87% Poly, 10% Rayon, 3% Spandex\nHand Wash (I use machine with hand wash cycle in lingerie bag)\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); 2XL (16) True To Size",
  "cat": "Dresses",
  "img": "img/products/anna-dress.jpg"
 },
 {
  "name": "Alli Pajama Set",
  "style": null,
  "price": "65",
  "sizes": "XS, S, M, L, XL, 1X, 2X",
  "desc": "94% Poly, 6% Spandex\nMachine Wash \nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); 1X (16); 2X (18)",
  "cat": "Sets & Pajamas",
  "img": "img/products/alli-pajama-set.jpg"
 },
 {
  "name": "Ginny Top & Shorts Set",
  "style": null,
  "price": "40",
  "sizes": "S, M, L, XL, XXL",
  "desc": "Sequin Designs/Draw String Elastic Shorts\n87% Poly, 10% Rayon, 3% Spandex\nHand Wash (I use machine with hand wash cycle in lingerie bag)\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); XXL (16) True To Size",
  "cat": "Sets & Pajamas",
  "img": "img/products/ginny-top-shorts-set.jpg"
 },
 {
  "name": "Lauren Top & Shorts Set",
  "style": null,
  "price": "40",
  "sizes": "S, M, L, XL",
  "desc": "Sequin Designs/Draw String Elastic Shorts\n87% Poly, 10% Rayon, 3% Spandex\nHand Wash (I use machine with hand wash cycle in lingerie bag)\nS (4-6); M (8-10); L (10-12); XL (14) True To Size",
  "cat": "Sets & Pajamas",
  "img": "img/products/lauren-top-shorts-set.jpg"
 },
 {
  "name": "Faith V-Neck Sweater",
  "style": null,
  "price": "109",
  "sizes": "XS, S, M, L, XL",
  "desc": "Beaded and Logo Design\n52% Viscose, 20% Poly, 28% Nylon\nMachine Wash Cold\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); Runs Small",
  "cat": "Sweatshirts & Sweaters",
  "img": "img/products/faith-v-neck-sweater.jpg"
 },
 {
  "name": "Sarah Sweatshirt Aubie",
  "style": null,
  "price": "99",
  "sizes": "XS, S, M, L, XL, 1X, 2X",
  "desc": "Embroidered/Beaded Design\n62% Poly, 33% Rayon, 5% Spandex\nHand Wash (I use machine with hand wash cycle in lingerie bag)\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); 1X (16); 2X (18) Generously sized",
  "cat": "Sweatshirts & Sweaters",
  "img": "img/products/sarah-sweatshirt-aubie.jpg"
 },
 {
  "name": "Millie Sweatshirt WDE",
  "style": null,
  "price": "99",
  "sizes": "XS, S, M, L, XL, 1X, 2X",
  "desc": "Rhinestone/Sequin Design\n62% Poly, 33% Rayon, 5% Spandex\nHand Wash (I use machine with hand wash cycle in lingerie bag)\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); 1X (16); 2X (18) Generously sized",
  "cat": "Sweatshirts & Sweaters",
  "img": "img/products/millie-sweatshirt-wde.jpg"
 },
 {
  "name": "Sarah Sweatshirt Varsity",
  "style": null,
  "price": "74",
  "sizes": "XS, S, M, L, XL, 1X, 2X",
  "desc": "Chenille/Beaded Design\n62% Poly, 33% Rayon, 5% Spandex\nHand Wash (I use machine with hand wash cycle in lingerie bag)\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); 1X (16); 2X (18) Generously sized",
  "cat": "Sweatshirts & Sweaters",
  "img": "img/products/sarah-sweatshirt-varsity.jpg"
 },
 {
  "name": "Millie Sweatshirt Script",
  "style": null,
  "price": "104",
  "sizes": "XS, S, M, L, XL, 1X, 2X",
  "desc": "Chenille Script Lettering\n62% Poly, 33% Rayon, 5% Spandex\nHand Wash (I use machine with hand wash cycle in lingerie bag)\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); 1X (16); 2X (18) Generously sized",
  "cat": "Sweatshirts & Sweaters",
  "img": "img/products/millie-sweatshirt-script.jpg"
 },
 {
  "name": "Tina Top War Eagle",
  "style": null,
  "price": "74",
  "sizes": "XS, S, M, L, XL, 1X, 2X",
  "desc": "Embroidered Rope Script Lettering\n62% Poly, 33% Rayon, 5% Spandex\nHand Wash (I use machine with hand wash cycle in lingerie bag)\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); 1X (16); 2X (18) True To Size",
  "cat": "Tops",
  "img": "img/products/tina-top-war-eagle.jpg"
 },
 {
  "name": "Tracey Dress Tiger",
  "style": null,
  "price": "92",
  "sizes": "XS, S, M, L, XL",
  "desc": "Gathered Waist with Pockets\n100% Poly\nMachine Wash Cold\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); True To Size",
  "cat": "Dresses",
  "img": "img/products/tracey-dress-tiger.jpg"
 },
 {
  "name": "Emily Top Icons",
  "style": null,
  "price": "89",
  "sizes": "XS, S, M, L, XL",
  "desc": "Embroidered Beaded Sequin Design\n62% Poly, 33% Rayon, 5% Spandex\nHand Wash (I use machine with hand wash cycle in lingerie bag)\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14) Generously sized",
  "cat": "Tops",
  "img": "img/products/emily-top-icons.jpg"
 },
 {
  "name": "Charlotte Pajama Set Toile",
  "style": null,
  "price": "92",
  "sizes": "XS, S, M, L, XL, 1X, 2X",
  "desc": "95% Viscose, 5% Spandex\nMachine Wash \nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14); 1X (16); 2X (18)",
  "cat": "Sets & Pajamas",
  "img": "img/products/charlotte-pajama-set-toile.jpg"
 },
 {
  "name": "Emily Top Mascot",
  "style": null,
  "price": "79",
  "sizes": "XS, S, M, L, XL",
  "desc": "Embroidered Beaded Sequin Design\n62% Poly, 33% Rayon, 5% Spandex\nHand Wash (I use machine with hand wash cycle in lingerie bag)\nXS (0-2); S (4-6); M (8-10); L (10-12); XL (14) Generously sized",
  "cat": "Tops",
  "img": "img/products/emily-top-mascot.jpg"
 },
 {
  "name": "Earrings Auburn Drop",
  "style": "75750",
  "price": "37",
  "sizes": "One Size",
  "desc": "AU Logo Drop Earrings With Large Stone Accent",
  "cat": "Earrings",
  "img": "img/products/earrings-auburn-drop.jpg"
 },
 {
  "name": "Earrings Auburn Pendant",
  "style": "75744",
  "price": "23",
  "sizes": "One Size",
  "desc": "AU Pendant Earrings On Small Gold Hoop",
  "cat": "Earrings",
  "img": "img/products/earrings-auburn-pendant.jpg"
 },
 {
  "name": "Earrings Aubie Pendant",
  "style": "75745",
  "price": "21",
  "sizes": "One Size",
  "desc": "Aubie Pendant Earrings On Small Gold Hoop",
  "cat": "Earrings",
  "img": "img/products/earrings-aubie-pendant.jpg"
 },
 {
  "name": "Earrings Aubie Hoop",
  "style": "75748",
  "price": "31",
  "sizes": "One Size",
  "desc": "Aubie Pendant On Navy/Gold Hoop",
  "cat": "Earrings",
  "img": null
 },
 {
  "name": "Earrings War Eagle Dangle",
  "style": "75746",
  "price": "29",
  "sizes": "One Size",
  "desc": "War Eagle Charm/Tiger Paw Charm/Blue Stone On Small Gold Hoop",
  "cat": "Earrings",
  "img": "img/products/earrings-war-eagle-dangle.jpg"
 },
 {
  "name": "Earrings WDE Drop",
  "style": "75752",
  "price": "27",
  "sizes": "One Size",
  "desc": "WDE Navy/Orange Logo Drop Earrings With Large White Beaded Accent",
  "cat": "Earrings",
  "img": "img/products/earrings-wde-drop.jpg"
 },
 {
  "name": "Earrings AU Hoop",
  "style": "75747",
  "price": "31",
  "sizes": "One Size",
  "desc": "AU Pendant On Navy/Gold Hoop",
  "cat": "Earrings",
  "img": "img/products/earrings-au-hoop.jpg"
 },
 {
  "name": "Earrings Aubie Pearl Drop",
  "style": "75749",
  "price": "17",
  "sizes": "One Size",
  "desc": "Aubie Acrylic Logo Drop Earrings With Large Pearl Accent",
  "cat": "Earrings",
  "img": "img/products/earrings-aubie-pearl-drop.jpg"
 }
];
